# Generated by Django 5.2.7 on 2025-12-25 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.FloatField(help_text='Capacidad en barriles o litros')),
                ('altura_referencia', models.FloatField(help_text='Altura de referencia del tanque en mm')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_medicion', models.CharField(choices=[('VACIO', 'Medición a Vacío'), ('FONDO', 'Medición a Fondo')], max_length=10)),
                ('temperatura_ambiente', models.FloatField(validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(135)])),
                ('nivel_automatico', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)])),
                ('temperatura_automatica', models.FloatField()),
                ('temp_liquido_superior', models.FloatField(validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(135)])),
                ('temp_liquido_media', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(135)])),
                ('temp_liquido_inferior', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(135)])),
                ('lectura_1_cinta_o_nivel', models.IntegerField()),
                ('lectura_1_plomada', models.IntegerField(blank=True, null=True)),
                ('lectura_2_cinta_o_nivel', models.IntegerField()),
                ('lectura_2_plomada', models.IntegerField(blank=True, null=True)),
                ('lectura_3_cinta_o_nivel', models.IntegerField(blank=True, null=True)),
                ('lectura_3_plomada', models.IntegerField(blank=True, null=True)),
                ('nivel_calculado_final', models.FloatField(blank=True, editable=False, null=True)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='mediciones.tanque')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
