# Generated by Django 5.2.7 on 2025-12-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('volumen_tov', models.FloatField(help_text='Total Observed Volume')),
                ('volumen_gsv', models.FloatField(blank=True, help_text='Gross Standard Volume (Calculated/Stored)', null=True)),
                ('volumen_nsv', models.FloatField(blank=True, help_text='Net Standard Volume (Calculated/Stored)', null=True)),
                ('tanque', models.ForeignKey(blank=True, help_text='Tanque al que se asigna esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='mediciones.tanque')),
            ],
        ),
    ]
