# Generated by Django 5.2.7 on 2025-12-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0002_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='volumen_gsv',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='volumen_nsv',
        ),
    ]
