# Generated by Django 5.2.7 on 2025-12-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0003_remove_linea_volumen_gsv_remove_linea_volumen_nsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='producto',
            field=models.CharField(default='Crudo', help_text='Producto contenido en el tanque', max_length=100),
        ),
    ]
