# Generated by Django 5.2.7 on 2025-12-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0004_medicion_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('api', models.FloatField(help_text='Gravedad API')),
                ('es_refinado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mediciones.cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='medicion',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto contenido en el tanque', null=True, on_delete=django.db.models.deletion.PROTECT, to='mediciones.producto'),
        ),
    ]
