# Generated by Django 5.2.7 on 2025-12-25 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0005_cliente_producto_alter_medicion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='producto_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques_con_producto', to='mediciones.producto'),
        ),
    ]
