# Generated by Django 5.2.7 on 2026-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0006_tanque_producto_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='api_observado',
            field=models.FloatField(blank=True, help_text='Gravedad API observada (1 decimal)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('COMPLETADA', 'Completada')], default='REGISTRADA', help_text='Estado del flujo de la medición', max_length=15),
        ),
        migrations.AddField(
            model_name='medicion',
            name='gsw',
            field=models.FloatField(blank=True, help_text='GSW (3 decimales)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='volumen_calculado',
            field=models.FloatField(blank=True, editable=False, help_text='Volumen final calculado al completar la medición', null=True),
        ),
    ]
