# Generated by Django 5.2.7 on 2026-03-29 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0007_medicion_api_observado_medicion_estado_medicion_gsw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del balance diario', unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'En Progreso'), ('CERRADO', 'Confirmado / Cerrado')], default='BORRADOR', max_length=15)),
                ('total_general', models.FloatField(default=0.0, help_text='Suma total de volumen de planta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance Diario',
                'verbose_name_plural': 'Balances Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_tanque', models.FloatField(default=0.0)),
                ('volumen_total', models.FloatField(default=0.0)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mediciones.balancediario')),
                ('lineas', models.ManyToManyField(blank=True, to='mediciones.linea')),
                ('medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediciones.medicion')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediciones.tanque')),
            ],
            options={
                'verbose_name': 'Detalle de Balance',
                'verbose_name_plural': 'Detalles de Balance',
                'unique_together': {('balance', 'tanque')},
            },
        ),
    ]
