# Generated by Django 5.2.7 on 2026-03-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0008_balancediario_detallebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='medios_transporte')),
            ],
        ),
    ]
