# Generated by Django 5.2.7 on 2026-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0009_mediotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediotransporte',
            name='icono',
            field=models.CharField(default='local_shipping', help_text="Nombre del icono de Material Design (ej: 'local_shipping', 'directions_boat')", max_length=50),
        ),
    ]
