# Generated by Django 5.2.7 on 2026-03-30 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0010_mediotransporte_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad movida (positiva o negativa)')),
                ('detalle_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='mediciones.detallebalance')),
                ('medio_transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediciones.mediotransporte')),
            ],
        ),
    ]
