# Generated by Django 5.2.7 on 2026-03-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0011_movimientotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebalance',
            name='volumen_inicial',
            field=models.FloatField(default=0.0, help_text='Volumen de cierre del balance anterior'),
        ),
    ]
