# Generated by Django 5.2.7 on 2026-03-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0012_detallebalance_volumen_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la medición está activa o deshabilitada'),
        ),
    ]
