# Generated by Django 5.2.7 on 2026-03-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0013_medicion_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='terminal_logos')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Datos de la Terminal / Empresa',
                'verbose_name_plural': 'Datos de la Terminal',
            },
        ),
    ]
