# Generated by Django 5.2.7 on 2026-03-30 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0014_terminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancediario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallebalance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='api_observado',
        ),
        migrations.AddField(
            model_name='medicion',
            name='api',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='api_60',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='ctl_factor',
            field=models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='ctsh_factor',
            field=models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='fra_valor',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='gov',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='gsv',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='nsv',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='temperatura_producto',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(135)]),
        ),
        migrations.AddField(
            model_name='medicion',
            name='tov',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_hidrocarburo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tanque',
            name='enchaquetamiento',
            field=models.BooleanField(default=False, help_text='Indica si el tanque tiene enchaquetamiento'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='requiere_api',
            field=models.BooleanField(default=True, help_text='Indica si el cálculo requiere gravedad API'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='zona_critica_L',
            field=models.FloatField(default=0, help_text='Altura de la zona crítica en mm'),
        ),
        migrations.AlterField(
            model_name='balancediario',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='balancediario',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detallebalance',
            name='tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mediciones.tanque'),
        ),
        migrations.AlterField(
            model_name='detallebalance',
            name='volumen_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallebalance',
            name='volumen_tanque',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallebalance',
            name='volumen_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='linea',
            name='tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='mediciones.tanque'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='volumen_tov',
            field=models.DecimalField(decimal_places=2, help_text='Total Observed Volume de la línea', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('COMPLETADA', 'Completada')], default='REGISTRADA', max_length=15),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='gsw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='nivel_automatico',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22000)]),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mediciones.producto'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='volumen_calculado',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='movimientotransporte',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='nit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='NombresDeTablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('api', models.IntegerField(blank=True, null=True)),
                ('ajuste_fra', models.FloatField(blank=True, null=True)),
                ('incremento_fra', models.FloatField(blank=True, null=True)),
                ('activa', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=20)),
                ('tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tanque_nombresTabla', to='mediciones.tanque')),
            ],
            options={
                'verbose_name_plural': 'Nombres De Tablas',
            },
        ),
        migrations.CreateModel(
            name='TablaDeAforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(blank=True, choices=[('Cm', 'Cm'), ('Mm', 'Mm')], max_length=30)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('barriles', models.FloatField(blank=True, null=True)),
                ('tabla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediciones.nombresdetablas')),
            ],
            options={
                'verbose_name_plural': 'Tablas De Aforo',
            },
        ),
        migrations.CreateModel(
            name='TablaDensidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField(help_text='Temperatura en °F (entero)')),
                ('densidad', models.DecimalField(decimal_places=5, help_text='Densidad en g/ml o kg/m3', max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablas_densidad', to='mediciones.producto')),
            ],
            options={
                'verbose_name': 'Tabla de Densidad',
                'verbose_name_plural': 'Tablas de Densidad',
                'unique_together': {('producto', 'temperatura')},
            },
        ),
    ]
