# Generated by Django 5.2.7 on 2026-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0015_alter_balancediario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='api_actual',
            field=models.FloatField(blank=True, help_text='Gravedad API actual del producto en el tanque', null=True),
        ),
    ]
