# Generated by Django 5.2.7 on 2026-03-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0016_tanque_api_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='api_60',
        ),
    ]
