# Generated by Django 5.2.7 on 2026-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0017_remove_medicion_api_60'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='api_60',
            field=models.FloatField(blank=True, editable=False, help_text='Gravedad API corregida a 60°F', null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='api',
            field=models.FloatField(blank=True, help_text='Gravedad API Observada', null=True),
        ),
    ]
