# Generated by Django 5.2.7 on 2026-04-05 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0018_medicion_api_60_alter_medicion_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='motivo',
            field=models.CharField(choices=[('MOVIMIENTO', 'Movimiento'), ('INVENTARIO', 'Inventario'), ('AUDITORIA', 'Auditoría')], default='MOVIMIENTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='nivel_automatico',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24000)]),
        ),
    ]
