# Generated by Django 5.2.7 on 2026-04-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0019_medicion_motivo_alter_medicion_nivel_automatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='motivo',
            field=models.CharField(blank=True, default='Movimiento', max_length=255),
        ),
    ]
